-- Tables for SDS Project
-- N.FAKIH 31/10/2022
-- for MySQL

-- Drop BRAND before creation
DROP TABLE IF EXISTS `BRAND`;
-- Creation
CREATE TABLE IF NOT EXISTS `BRAND` (
    `ID` BIGINT  PRIMARY KEY  NOT NULL ,
    `CODE` VARCHAR(20)  UNIQUE ,
    `LABEL` VARCHAR(50) );

-- Drop MODULE before creation
DROP TABLE IF EXISTS `MODULE`;
-- Creation
CREATE TABLE `MODULE` (
    `ID` BIGINT  PRIMARY KEY  NOT NULL ,
    `CODE` VARCHAR(20)  UNIQUE ,
    `LABEL` VARCHAR(50) );

-- Drop PARTNER before creation
DROP TABLE IF EXISTS `PARTNER`;
-- Creation
CREATE TABLE `PARTNER` (
    `ID` BIGINT  PRIMARY KEY  NOT NULL ,
    `CODE` VARCHAR(20)  UNIQUE ,
    `LABEL` VARCHAR(50) ,
    `IDBRAND` BIGINT DEFAULT 0,
    `ACTIVATED` TINYINT DEFAULT 0,
    `EMAIL` VARCHAR(128)  UNIQUE ,
    `PWD` VARCHAR(64) );
CREATE INDEX `WDIDX_PARTNER_IDBRAND` ON `PARTNER` (`IDBRAND`);
CREATE INDEX `WDIDX_PARTNER_ACTIVATED` ON `PARTNER` (`ACTIVATED`);
CREATE INDEX `WDIDX_PARTNER_PWD` ON `PARTNER` (`PWD`);

-- Drop PARTNER_MODULE before creation
DROP TABLE IF EXISTS `PARTNER_MODULE`;
-- Creation
CREATE TABLE `PARTNER_MODULE` (
    `IDMODULE` BIGINT ,
    `IDPARTNER` BIGINT ,
    `MODULE_ALLOWED` TINYINT DEFAULT 0);
CREATE INDEX `WDIDX_PARTNER_MODULE_IDMODULE` ON `PARTNER_MODULE` (`IDMODULE`);
CREATE INDEX `WDIDX_PARTNER_MODULE_IDPARTNER` ON `PARTNER_MODULE` (`IDPARTNER`);
CREATE INDEX `WDIDX_PARTNER_MODULE_MODULE_ALLOWED` ON `PARTNER_MODULE` (`MODULE_ALLOWED`);
CREATE UNIQUE INDEX `WDIDX_PARTNER_MODULE_IDPARTNER_IDMODULE` ON `PARTNER_MODULE` (`IDPARTNER`,`IDMODULE`);

-- Drop SPORT_ROOM before creation
DROP TABLE IF EXISTS `SPORT_ROOM`;
-- Creation
CREATE TABLE `SPORT_ROOM` (
    `ID` BIGINT  PRIMARY KEY  NOT NULL ,
    `CODE` VARCHAR(20)  UNIQUE ,
    `LABEL` VARCHAR(50) ,
    `IDPARTNER` BIGINT DEFAULT 0,
    `ACTIVATED` TINYINT DEFAULT 0,
    `EMAIL` VARCHAR(128)  UNIQUE ,
    `PWD` VARCHAR(64) ,
    `ADDRESS` VARCHAR(256) ,
    `ZIPCODE` VARCHAR(20) ,
    `CITY` VARCHAR(50) ,
    `COUNTRY` VARCHAR(50) );
CREATE INDEX `WDIDX_SPORT_ROOM_IDPARTNER` ON `SPORT_ROOM` (`IDPARTNER`);
CREATE INDEX `WDIDX_SPORT_ROOM_ACTIVATED` ON `SPORT_ROOM` (`ACTIVATED`);
CREATE INDEX `WDIDX_SPORT_ROOM_PWD` ON `SPORT_ROOM` (`PWD`);

-- Drop SPORT_ROOM_MODULE before creation
DROP TABLE IF EXISTS `SPORT_ROOM_MODULE`;
-- Creation
CREATE TABLE `SPORT_ROOM_MODULE` (
    `IDMODULE` BIGINT ,
    `IDSPORT_ROOM` BIGINT ,
    `MODULE_ALLOWED` TINYINT DEFAULT 0);
CREATE INDEX `WDIDX_SPORT_ROOM_MODULE_IDMODULE` ON `SPORT_ROOM_MODULE` (`IDMODULE`);
CREATE INDEX `WDIDX_SPORT_ROOM_MODULE_IDSPORT_ROOM` ON `SPORT_ROOM_MODULE` (`IDSPORT_ROOM`);
CREATE INDEX `WDIDX_SPORT_ROOM_MODULE_MODULE_ALLOWED` ON `SPORT_ROOM_MODULE` (`MODULE_ALLOWED`);
CREATE UNIQUE INDEX `WDIDX_SPORT_ROOM_MODULE_IDSPORT_ROOM_IDMODULE` ON `SPORT_ROOM_MODULE` (`IDSPORT_ROOM`,`IDMODULE`);

-- integrity constraints
ALTER TABLE `PARTNER` ADD FOREIGN KEY (`IDBRAND`) REFERENCES `BRAND` (`ID`);
ALTER TABLE `SPORT_ROOM` ADD FOREIGN KEY (`IDPARTNER`) REFERENCES `PARTNER` (`ID`);
ALTER TABLE `SPORT_ROOM_MODULE` ADD FOREIGN KEY (`IDSPORT_ROOM`) REFERENCES `SPORT_ROOM` (`ID`);
ALTER TABLE `SPORT_ROOM_MODULE` ADD FOREIGN KEY (`IDMODULE`) REFERENCES `MODULE` (`ID`);
ALTER TABLE `PARTNER_MODULE` ADD FOREIGN KEY (`IDPARTNER`) REFERENCES `PARTNER` (`ID`);
ALTER TABLE `PARTNER_MODULE` ADD FOREIGN KEY (`IDMODULE`) REFERENCES `MODULE` (`ID`);
